version: '3.8'

services:
  ebytr:
    build: .
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
      ME_CONFIG_MONGODB_URL: mongodb://docker:docker@mongo:27017/

volumes:
  node_modules:
